name: Deploy to Server

on:
  push:
    branches:
      - main  # Desplegar cuando se haga push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.1'

      - name: Install dependencies
        run: |
          npm install

      - name: Build project
        run: |
          npm run build  # Este paso debe ser ejecutado en el servidor, si no se ha hecho antes

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}  # IP del servidor
          username: ${{ secrets.SERVER_USER }}  # Usuario del servidor
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Clave privada para SSH
          port: 2225  # Aquí definimos el puerto 2225 en lugar del puerto 22
          script: |
            cd /home/reno7882/proyectos/strapi  # Carpeta en el servidor
            git pull origin main  # Hacer pull de la rama main
            npm install  # Instalar dependencias
            npm run build  # Ejecutar build para generar la carpeta dist
            
            # Reiniciar la aplicación Strapi con las nuevas variables de entorno
            pm2 status strapi-app || echo "Error al reiniciar Strapi"
